image: docker:stable

services:
  - name: docker:dind
    command: ["dockerd-entrypoint.sh"]
    entrypoint: ["env", "-u", "DOCKER_HOST"]

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
   - docker build -t register.gitlab.com/nalaginrut/artanis:latest .
   - docker push register.gitlab.com/nalaginrut/artanis:latest
  only:
    - docker
  
stages:
  - build
