image: docker:stable

services:
  - name: docker:dind
    command: ["dockerd-entrypoint.sh"]
    entrypoint: ["env", "-u", "DOCKER_HOST"]

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""

before_script:
  - echo -n $CI_JOB_TOKEN | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin

build:
  stage: build
  script:
   - docker build -t $CI_REGISTRY/HardenedLinux/artanis:latest .
   - docker push $CI_REGISTRY/HardenedLinux/artanis:latest
  only:
    - docker
  
stages:
  - build
